### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by xsawyerx** [yanick/Dist-Zilla-Plugin-CoalescePod#1] opened 2016-01-03 18:18 UTC
I can't install [PluginBundle::YANICK](https://metacpan.org/pod/Dist::Zilla::PluginBundle::YANICK) because this plugin fails installing. :/

**Comment by xsawyerx** [comment] 2016-01-03 18:19
Here is my output:

```
t/basic.t ..................... 1/3
#   Failed test 'pod files are removed'
#   at t/basic.t line 12.
#          got: '1'
#     expected: '0'

#   Failed test 'pod before __DATA__'
#   at t/basic.t line 20.
#                   'package Data;
# # ABSTRACT: with Data
#
# use strict;
# use warnings;
#
# 1;
#
# __DATA__
#
#
#
# '
#     doesn't match '(?^s:=head1 DESCRIPTION.*__DATA__)'
# Looks like you failed 2 tests of 3.
t/basic.t ..................... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests
```

**Comment by mcmillhj** [comment] 2016-01-04 20:20
I was assigned this dist for the CPAN PR challenge and was able to install without issue. Since there are no other existing issues I am happy to look into this one. Would you mind telling me what platform and Perl version you were using so I can try to reproduce the issue?

**Comment by xsawyerx** [comment] 2016-01-04 23:43
Happily!

Platform: `GNU/Linux, x86_64`
Perl: `v5.18.2`
Dist::Zilla: `5.042`

**Comment by mcmillhj** [comment] 2016-01-05 15:35
I seem unable to reproduce this with the same version of Perl, Dist::Zilla, and on Linux (Gentoo). Is there anything else different about your environment? System Perl vs brewed Perl? etc...

**Comment by yanick** [comment] 2016-01-05 15:37
Hint, running `perl t/000-report-versions-tiny.t` provides all the yummy information we might want. :-)

**Comment by yanick** [comment] 2016-01-05 15:37
And, for the record, the tests are passing on my machine as well.

**Comment by yanick** [comment] 2016-01-05 15:39
For reference: http://matrix.cpantesters.org/?dist=Dist-Zilla-Plugin-CoalescePod+0.2.2

**Comment by xsawyerx** [comment] 2016-01-05 17:24
The entire output, for those playing at home. :)

```
Entering Dist-Zilla-Plugin-CoalescePod-0.2.2
Checking configure dependencies from META.json
Checking if you have Module::Build 0.28 ... Yes (0.4210)
Checking if you have Module::Build 0.36 ... Yes (0.4210)
Running Build.PL
Configuring Dist-Zilla-Plugin-CoalescePod-0.2.2 ... Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Dist-Zilla-Plugin-CoalescePod' version '0.2.2'
OK
Checking dependencies from MYMETA.json ...
Checking if you have Dist::Zilla::Role::FileMunger 0 ... Yes (5.042)
Checking if you have strict 0 ... Yes (1.07)
Checking if you have Moose 0 ... Yes (2.1603)
Checking if you have warnings 0 ... Yes (1.18)
Checking if you have Test::DZil 0 ... Yes (5.042)
Checking if you have File::Spec 0 ... Yes (3.40)
Checking if you have IO::Handle 0 ... Yes (1.34)
Checking if you have Test::More 0.88 ... Yes (1.001014)
Checking if you have IPC::Open3 0 ... Yes (1.13)
Checking if you have Module::Build 0.28 ... Yes (0.4210)
Building and testing Dist-Zilla-Plugin-CoalescePod-0.2.2 ... Building Dist-Zilla-Plugin-CoalescePod
t/00-compile.t ................ ok   
t/000-report-versions-tiny.t .. # 
# 
# Generated by Dist::Zilla::Plugin::ReportVersions::Tiny v1.10
# perl: 5.018002 (wanted 5.006) on linux from /usr/bin/perl
# 
# Dist::Zilla::Role::FileMunger                 => 5.042      (want any version)
# File::Spec                                    => 3.40       (want any version)
# IO::Handle                                    => 1.34       (want any version)
# IPC::Open3                                    => 1.13       (want any version)
# Module::Build                                 => 0.421      (want 0.28)   
# Moose                                         => 2.1603     (want any version)
# Test::DZil                                    => 5.042      (want any version)
# Test::More                                    => 1.001014   (want 0.88)   
# strict                                        => 1.07       (want any version)
# warnings                                      => 1.18       (want any version)
# 
# Thanks for using my code.  I hope it works for you.
# If not, please try and include this output in the bug report.
# That will help me reproduce the issue and solve your problem.
# 
t/000-report-versions-tiny.t .. ok   
t/basic.t ..................... 1/3 
#   Failed test 'pod files are removed'
#   at t/basic.t line 12.
#          got: '1'
#     expected: '0'

#   Failed test 'pod before __DATA__'
#   at t/basic.t line 20.
#                   'package Data;
# # ABSTRACT: with Data
# 
# use strict;
# use warnings;
# 
# 1;
# 
# __DATA__
# 
# 
# 
# '
#     doesn't match '(?^s:=head1 DESCRIPTION.*__DATA__)'
# Looks like you failed 2 tests of 3.
t/basic.t ..................... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests 

Test Summary Report
-------------------
t/basic.t                   (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  1, 3
  Non-zero exit status: 2
Files=3, Tests=5,  3 wallclock secs ( 0.03 usr  0.01 sys +  2.12 cusr  0.13 csys =  2.29 CPU)
Result: FAIL
Failed 1/3 test programs. 2/5 subtests failed.
FAIL
! Installing Dist::Zilla::Plugin::CoalescePod failed. See /home/sawyer/.cpanm/work/1452014571.30499/build.log for details. Retry with --force to force install it.
```

**Comment by xsawyerx** [comment] 2016-01-05 17:25
The `000-report-versions-tiny.t` does not cover whether it's 32 or 64, apparently.

**Comment by mcmillhj** [comment] 2016-01-05 18:43
Still can't seem to re-create, I installed the same modules versions and did not encounter an error:

```
[hunter@apollo: Dist-Zilla-Plugin-CoalescePod-0.2.2]$ perl Build.PL 
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Dist-Zilla-Plugin-CoalescePod' version '0.2.2'
[hunter@apollo: Dist-Zilla-Plugin-CoalescePod-0.2.2]$ ./Build && ./Build test
Building Dist-Zilla-Plugin-CoalescePod
t/00-compile.t ................ ok   
t/000-report-versions-tiny.t .. # 
# 
# Generated by Dist::Zilla::Plugin::ReportVersions::Tiny v1.10
# perl: 5.018002 (wanted 5.006) on linux from /home/hunter/perl5/perlbrew/perls/perl-5.18.2/bin/perl
# 
# Dist::Zilla::Role::FileMunger                 => 5.042      (want any version)
# File::Spec                                    => 3.40       (want any version)
# IO::Handle                                    => 1.34       (want any version)
# IPC::Open3                                    => 1.13       (want any version)
# Module::Build                                 => 0.421      (want 0.28)   
# Moose                                         => 2.1603     (want any version)
# Test::DZil                                    => 5.042      (want any version)
# Test::More                                    => 1.001014   (want 0.88)   
# strict                                        => 1.07       (want any version)
# warnings                                      => 1.18       (want any version)
# 
# Thanks for using my code.  I hope it works for you.
# If not, please try and include this output in the bug report.
# That will help me reproduce the issue and solve your problem.
# 
t/000-report-versions-tiny.t .. ok   
t/basic.t ..................... ok   
All tests successful.
Files=3, Tests=5,  2 wallclock secs ( 0.01 usr  0.01 sys +  1.60 cusr  0.05 csys =  1.67 CPU)
Result: PASS
```

**Comment by xsawyerx** [comment] 2016-01-05 22:34
Here's some additional data. When the test runs, it works on the files in the `corpus` directory. It should go over every file, but here are the files I see it go over:

```
"dist.ini"
"lib/Foo.pod"
"lib/Foo.pm"
"lib/Data.pod"
"META.yml"
"LICENSE"
"README"
"Makefile.PL"
```

You will notice it doesn't receive `lib/Data.pm`. I'm not sure why yet.

**Comment by xsawyerx** [comment] 2016-01-05 22:34
Compared with the files that exist:

```
t/corpus/
├── dist.ini
└── lib
    ├── Data.pm
    ├── Data.pod
    ├── Foo.pm
    └── Foo.pod
```

**Comment by xsawyerx** [comment] 2016-01-05 23:00
More information: `dzil` actually runs twice during the test. The first runs through [ExtraTests](https://metacpan.org/pod/Dist::Zilla::Plugin::ExtraTests), which goes over the file. The second runs through [CoalescePod](https://metacpan.org/pod/Dist::Zilla::Plugin::CoalescePod), which then does not have that file:

```
[munge_file ExtraTests]: dist.ini
[munge_file ExtraTests]: lib/Foo.pod
[munge_file ExtraTests]: lib/Foo.pm
[munge_file ExtraTests]: lib/Data.pm
[munge_file ExtraTests]: lib/Data.pod
[munge_file ExtraTests]: META.yml
[munge_file ExtraTests]: LICENSE
[munge_file ExtraTests]: README
[munge_file ExtraTests]: Makefile.PL
[munge_file in CoalescePod]: dist.ini
[munge_file in CoalescePod]: lib/Foo.pod
[munge_file in CoalescePod]: lib/Foo.pm
[munge_file in CoalescePod]: lib/Data.pod
[munge_file in CoalescePod]: META.yml
[munge_file in CoalescePod]: LICENSE
[munge_file in CoalescePod]: README
[munge_file in CoalescePod]: Makefile.PL
```

I'm not sure why it goes through that plugin (it's not in the `dist.ini`) and I'm not sure why when it runs through CoalescePod, the file is not there anymore.

**Comment by xsawyerx** [comment] 2016-01-05 23:10
Another update: I still don't understand why it goes through that plugin, but I know it's unrelated. It has the proper list before calling the plugin. When calling the plugin, it doesn't call the `munge_file` method with `Data.pm`. I suspect the module has something to do with it. Investigating further...

**Comment by xsawyerx** [comment] 2016-01-05 23:53
More.

When the plugin calls `$self->zilla->prune_file($podfile);` with `lib/Foo.pod`, for some reason, it screws up stuff with `lib/Data.pm`. Interestingly, this is happening because Dist::Zilla's code is written as:

```
for my $file ( @{ $self->zilla->files } ) {
  ...
  $self->munge_file($file);
}
```

If it was written as such, it works:

```
my @files = @{ $self->zilla->files };
for my $file (@files) {
  ...
  $self->munge_file($file);
}
```

**Comment by xsawyerx** [comment] 2016-01-06 00:07
The `prune_file()` method uses a `splice` to remove a file from an array. Even though it _seems_ like it's removing the right file, from that point on, it doesn't call `lib/Data.pm`. I think this is due to the position we have in the array and it being spliced mid-way.

If `lib/Foo.pm` comes right before `lib/Data.pm` and `lib/Foo.pm` causes a splice of one item, and - if due to the this - the next element is skipped, the element that is then skipped is `lib/Data.pm`. This would explain it.

However, I have **no idea** why this only happens for me. :/

**Comment by xsawyerx** [comment] 2016-01-06 00:14
Ah! Here are additional reports on it:
- http://www.cpantesters.org/cpan/report/a45ed2f6-8779-11e5-add7-7a6fe0bfc7aa
- http://www.cpantesters.org/cpan/report/c2dd2a0a-b02a-11e5-bbfb-2fd8fcd2507e
- http://www.cpantesters.org/cpan/report/4662852a-055c-11e5-920f-7823e0bfc7aa
- http://www.cpantesters.org/cpan/report/79fbc982-2528-11e5-a158-770ce0bfc7aa
- http://www.cpantesters.org/cpan/report/9c6640f4-d061-11e4-8e5f-f6c9dfbfc7aa
- http://www.cpantesters.org/cpan/report/7bab83b0-cdaf-11e4-956b-4af1e0bfc7aa
- http://www.cpantesters.org/cpan/report/29fdcae2-abdf-11e4-8c61-d1dbe0bfc7aa

**Comment by mcmillhj** [comment] 2016-01-06 01:06
Interesting, I am not sure I understand the difference between these two 

```
for my $file ( @{ $self->zilla->files } ) {
  ...
  $self->munge_file($file);
}
```

```
my @files = @{ $self->zilla->files };
for my $file (@files) {
  ...
  $self->munge_file($file);
}
```

Also, How exactly are you stepping through the build process? I would love to step through but I am not sure which tools to use. 

I had thought I would just 

```
perl Build.PL
perl -d ./Build test 
```

but I am not making much headway.

**Comment by yanick** [comment] 2016-01-06 01:19
On 2016-01-05 08:06 PM, Hunter McMillen wrote:

> Interesting, I am not sure I understand the difference between these two
> 
> |for my $file ( @{ $self->zilla->files } ) {
>   ...
>   $self->munge_file($file);
> }
> |
> 
> |my @files = @{ $self->zilla->files };
> for my $file (@files) {
>   ...
>   $self->munge_file($file);
> }
> |

In the first case, it's a reference to the original structure in zilla.
So if the munge_file does something to it, it'll mess with the loop.

To take a simpler example:

```
use strict;
use warnings;

use 5.10.0;

my @array = ( 1, 2, 3 );

for my $x ( @array ) {
    say $x;
    pop @array if $x == 2;
}


@array = ( 1, 2, 3 );
my @copy = @array;
for my $x ( @copy ) {
    say $x;
    pop @array if $x == 2;
}



```

**Comment by yanick** [comment] 2016-01-06 01:23
On 2016-01-05 08:06 PM, Hunter McMillen wrote:

> How exactly are you stepping through the build process?

https://metacpan.org/release/Dist-Zilla-App-Command-dumpphases  is
pretty useful for that.

`/.

**Comment by xsawyerx** [comment] 2016-01-06 07:53
Honestly, I usually take a pretty dumb-down approach to this.

I go into the directory and run:

```
perl -MDDP -Ilib t/basic.t
```

The `-MDDP` loads [Data::Printer](https://metacpan.org/pod/Data::Printer) (it's an alternative short name) into the `main` package. Then I can open any module I want (`vi lib/Dist/Zilla/Plugin/CoalescePod.pm`, `vi ~/perl5/lib/perl5/Dist/Zilla/Role/FileMunger.pm`) and debug variables with `::p $var`. `p` is the function provided by [Data::Printer](https://metacpan.org/pod/Data::Printer) and `::` at the beginning is the equivalent of running `main::p` (since I used `-MDDP`, I have DDP loaded in the `main` package, so that works).

When I want to walk down the stack to see where a call came from, I usually add a `warn` statement and then call the test again with `perl -MCarp::Always ...`, which will turn that single `warn` statement into a full stack, and I can see where an error originated.

I will sometimes add the following snippet:

```
my @c=caller;::p@c;
```

Which will provide me with the caller information (one stack above where I am) so I would know who called this function. This is a shorter version of `-MCarp::Always`, as it only gives one stack frame, but it's very useful.

Does that help?

**Comment by xsawyerx** [comment] 2016-01-06 07:54
I do sometimes reach for the Perl debugger, but despite how powerful it is, it is hard for me to remember all the keystrokes and behaviors of it, so it can take me longer, and it's not as fun. With the Perl debugger, I can just set a breakpoint, continue to it, then walk each subroutine while inspecting the variables. I find that process slower though. More calculated, but definitely slower. Then again, maybe if I practice it enough... :)

**Comment by mcmillhj** [comment] 2016-01-06 14:59
Thanks, these replies were extremely helpful. Going to dig in some more this afternoon after work.

**Comment by xsawyerx** [comment] 2016-01-06 15:22
@mcmillhj Happy to help! :)

I've spoken to rjbs. He wanted me to open a ticket against dzil for this as well. Aside from that, do consider that changing the files you're going over is possibly wrong from the plugins' side. If there is another way to receive the files in a different phase and remove them there, that would be more correct.

That's something I believe rjbs could help with. Once I create the ticket with Dist::Zilla, I'll link it to here and back.

**Comment by mcmillhj** [comment] 2016-01-11 23:20
I have played around with making CoalescePod also consume the FileGatherer or FilePruner roles in attempt to move the prune to a different build phase, but from my experimentation and from looking at the phase order in https://metacpan.org/source/RJBS/Dist-Zilla-5.043/lib/Dist/Zilla/Dist/Builder.pm#L335 (I should have done this first), it looks the FileMunger phase comes after both of these phases and excluding POD files from the Gather phase or pruning POD files in the Prune phase means they wont be available when the Munging phase occurs.  

I am not sure what other phase the prune could be moved to. There are phases _after_ the Munge phase, but I am not sure they are the appropriate place to delete files.

**Comment by xsawyerx** [comment] 2016-01-23 17:07
Let me create a ticket for this on Dist::Zilla.

**Comment by karenetheridge** [comment] 2016-01-25 19:42
Okay, so here's my understanding of the problem:
- you want to find a .pod file in the distribution, take its contents and add it to the corresponding .pm, and remove the .pod file from the build.
- modifying the .pm is (correctly) done in the filemunging phase.
- removing a file from the build should either be done in the gathering phase (which comes first), or in the pruning phase (after gathering, but before munging).  But if it is pruned in the pruning phase, the subsequent munging phase for the .pm file can't spot the .pod.

So, what to do?

Right now (https://metacpan.org/source/YANICK/Dist-Zilla-Plugin-CoalescePod-0.2.2/lib/Dist/Zilla/Plugin/CoalescePod.pm#L22-23) you're grabbing the .pod file from `$zilla->files` while the .pm file is being munged, and pruning the file right then and there.  Instead, add a `prune_files` sub to the plugin which finds and prunes the appropriate .pod files. **Cache those file(s) in a private attribute on the plugin, and prune them from the build.**  Then the plugin's `munge_files` can munge the .pm using the .pod files in the attribute, instead of looking for them in `$zilla->files`.

This also saves other plugins from munging the .pod file(s) in the build (which may run before CoalescePod gets around to pruning them). Since those files shouldn't be shipped, we don't want any other plugins to know they exist. (e.g. `[Test::Compile]` makes a list of all module files in the build and populates its own list of "files to test" - if that plugin appears before CoalesePod in dist.ini or your bundle, the compile test will fail because it will be attempting to open a file that does not exist.)

**Comment by mcmillhj** [comment] 2016-01-30 01:55
This makes a lot of sense. I will work on a PR that implements this solution.

**Comment by yanick** [comment] 2021-01-18 18:01
Finally fixed!

**Closed as completed by yanick** 2021-01-18 18:01 UTC
